aws:
  credentials:
    accessKeyID: "${NYCARES_AWS_ACCESS_KEY_ID}"
    secretAccessKey: "${NYCARES_AWS_SECRET_ACCESS_KEY}"
    region: "${NYCARES_AWS_REGION}"
  dynamo:
    tableName: "nycares-${NYCARES_ENV}-table"
    endpoint: "${NYCARES_DYNAMO_ENDPOINT}" # Optional, for local development
  s3:
    bucketName: "nycare-${NYCARES_ENV}-bucket"
    endpoint: "${NYCARES_S3_ENDPOINT}"
  sns:
    topicArn: "${NYCARES_SNS_TOPIC_ARN}"
  sf:
    callbackEndpoint: "${NYCARES_SF_CALLBACK_ENDPOINT}"
    approvalSecret: "${NYCARES_SF_APPROVAL_SECRET}"

auth:
  account:
    username: "${NYCARES_AUTH_USERNAME}"
    password: "${NYCARES_AUTH_PASSWORD}"
# Environment-specific settings can be overridden in the respective environment files
